[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "geohash"
version = "0.0.0"
authors = [
    { name = "David P. Chassin", email = "dchassin@eudoxys.com" }
]
description = "Eudoxys geohash tools"
readme = "README.md"
requires-python = ">=3.10"
keywords = ["eudoxys","geohash"]
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
]

[tool.setuptools]
packages = [
    "geohash"
]

[project.scripts]
geohash = "geohash:main"